# Translates data

The main goal of this notebook is to translate the data of this project from Spanish to English. I tried to use `googletrans` API but it is not currenlty working, so I created couple dictionaries to make translation by brute force.

## Downloading data from Google Drive

In [1]:
# To download the data from Google Drive
# !pip install gdown
import gdown

## To download the file: 'saber_11_pro.csv'
#url = 'https://drive.google.com/uc?export=download&id=1XKcjj7eEAmgmbHU4Qa7g2fUbHHXRkCBi'
#output = '../../data/saber_11_pro.csv'

## To download the file: 'saber_combined_all_fields.csv' <<< Use this by recommendation of the project manager
url = 'https://drive.google.com/uc?export=download&id=10OhmdA_gI3EDYj0IS0uUKsYDot_IBUnu'
output = '../../data/saber_combined_all_fields.csv'
gdown.download(url, output, quiet=False)

Downloading...
From: https://drive.google.com/uc?export=download&id=10OhmdA_gI3EDYj0IS0uUKsYDot_IBUnu
To: /Users/vcuspinera/Documents/levic/Projects_git/omdena-colombia-career-recommender-system/src/data/saber_combined_all_fields.csv
294MB [00:48, 6.04MB/s]

'../../data/saber_combined_all_fields.csv'

## Libraries

In [2]:
import numpy as np
import pandas as pd
# import matplotlib.pyplot as plt
# import seaborn as sns
# import gc
import ast
pd.set_option('display.max_rows', 500) # to show more rows.

## Load data

In [7]:
df = pd.read_csv('../../data/saber_combined_all_fields.csv')
df = df.drop(columns = 'Unnamed: 0')
df

,estu_tipodocumento,estu_nacionalidad,estu_genero,estu_fechanacimiento,estu_exterior,periodo,estu_consecutivo,estu_estadocivil,estu_estudiante,estu_pais_reside,...,punt_biologia,punt_quimica,punt_fisica,punt_ciencias_sociales,punt_filosofia,punt_ingles,desemp_ingles,profundiza,puntaje_prof,desemp_prof
0,TI,COLOMBIA,M,30/07/1996,NaN,20134,EK201340233804,Soltero,ESTUDIANTE,COLOMBIA,...,39.0,42.0,33.0,33.0,29.0,38.0,A-,PUNT_INTERDISC_MEDIOAMBIENTE,49.0,NaN
1,CC,COLOMBIA,M,13/04/1994,NaN,20133,EK201330220754,Soltero,ESTUDIANTE,COLOMBIA,...,52.0,52.0,54.0,44.0,47.0,51.0,A1,PUNT_PROFUNDIZA_LENGUAJE,6.0,II
2,CC,COLOMBIA,F,08/12/1991,NaN,20134,EK201340246502,Soltero,ESTUDIANTE,COLOMBIA,...,50.0,51.0,28.0,46.0,45.0,43.0,A-,PUNT_PROFUNDIZA_BIOLOGIA,5.0,I
3,TI,COLOMBIA,F,10/01/1996,NaN,20134,EK201340237996,Soltero,ESTUDIANTE,COLOMBIA,...,34.0,35.0,45.0,42.0,40.0,43.0,A-,PUNT_INTERDISC_VIOLENCIAYSOC,29.0,NaN
4,CC,COLOMBIA,M,11/10/1995,NO,20173,EK201730119521,NaN,ESTUDIANTE,COLOMBIA,...,57.0,65.0,44.0,49.0,43.0,42.0,A-,PUNT_INTERDISC_MEDIOAMBIENTE,55.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
212005,CC,COLOMBIA,F,18/07/1997,NO,20183,EK201830051813,Soltero,ESTUDIANTE,COLOMBIA,...,49.0,54.0,70.0,53.0,52.0,58.0,A2,PUNT_PROFUNDIZA_LENGUAJE,6.0,II
212006,CC,COLOMBIA,F,04/09/1995,NO,20183,EK201830033770,Soltero,ESTUDIANTE,COLOMBIA,...,68.0,56.0,55.0,60.0,42.0,75.0,B1,PUNT_PROFUNDIZA_BIOLOGIA,5.0,I
212007,CC,COLOMBIA,F,21/10/1971,NO,20183,EK201830110470,Casado,ESTUDIANTE,COLOMBIA,...,43.0,29.0,46.0,40.0,34.0,38.0,A-,PUNT_INTERDISC_MEDIOAMBIENTE,52.0,NaN
212008,CC,COLOMBIA,M,10/08/1994,NO,20183,EK201830148018,Soltero,ESTUDIANTE,COLOMBIA,...,42.0,46.0,45.0,44.0,33.0,43.0,A-,PUNT_INTERDISC_MEDIOAMBIENTE,52.0,NaN
212009,CC,COLOMBIA,M,01/01/1997,NO,20183,EK201830033403,Soltero,ESTUDIANTE,COLOMBIA,...,57.0,61.0,56.0,69.0,69.0,50.0,A1,PUNT_PROFUNDIZA_MATEMATICA,6.0,II

## Translate the feature columns
### Google translates API 
#### _⚠️ this approach didn't work_

I tried `pip install googletrans` in its different versions, but didn't work:
- `googletrans`
- `googletrans==3.1.0a0`
- `googletrans==4.0.0rc1`

> **Error: 'NoneType' object has no attribute 'group'**

I also tried `pip install google_trans_new`, and it return the next msg:
> **Error: Extra data: line 1 column 342 (char 341)**

You can run the two code chunks with examples to see the errors:

In [3]:
# #!pip install googletrans==4.0.0rc1

# translator = Translator()
# translation = translator.translate("Der Himmel ist blau und ich mag Bananen", dest='en')
# print(translation.text)
# #output: 'The sky is blue and I like bananas'

In [4]:
# # !pip install google_trans_new
# from google_trans_new import google_translator  
  
# translator = google_translator()  
# translate_text = translator.translate('Hola mundo!', lang_src='es', lang_tgt='en')  
# print(translate_text)

## Brute force translation
I made a dictionart to translate the headers of shorter `saber_combined_all_fields.csv` and larger `saber_11_pro.csv` databases for this project, as well as the variables of the data (based on the shorter database).

### Translates values

In [8]:
# open dictionary with dictionary of values for variables
file = open("../../data/translate_cat.txt", "r")
contents = file.read()
my_dics = ast.literal_eval(contents)
file.close()

# select cathegorical columns
cat_col=df.select_dtypes(include='object').columns.to_list()

# translates to English the values of the data frame
df_2 = df.copy()
for i in cat_col:
    try:
        df_2.replace({i: my_dics[i]}, inplace=True)
    except:
        next

### Translates header

In [9]:
# open dictionary of translated headers
file = open("../../data/translate_headers.txt", "r")
contents = file.read()
file.close()

# get headers as dictionary 
my_headers = ast.literal_eval(contents) #capital letters
my_headers_low = ast.literal_eval(contents.lower()) #lower case

# translate header
df_2 = df_2.rename(columns=my_headers_low)#, inplace=True)

In [10]:
# DataFrame translated to English
df_2.tail()

,your_type_of_document,your_nationality,your_gender,your_birthdate,your_exterior,period,your_consecutive,your_marital_status,your_student,your_country_resides,...,score_biology,score_chemistry,score_physical,score_social_science,score_philosophy,score_english,performance_english,go_deep,score_prof,performance_prof
212005,CC,COLOMBIA,F,18/07/1997,NO,20183,EK201830051813,Single,STUDENT,COLOMBIA,...,49.0,54.0,70.0,53.0,52.0,58.0,A2,SCORE_DEEPEN_LANGUAGE,6.0,II
212006,CC,COLOMBIA,F,04/09/1995,NO,20183,EK201830033770,Single,STUDENT,COLOMBIA,...,68.0,56.0,55.0,60.0,42.0,75.0,B1,SCORE_DEEPEN_BIOLOGY,5.0,I
212007,CC,COLOMBIA,F,21/10/1971,NO,20183,EK201830110470,Married,STUDENT,COLOMBIA,...,43.0,29.0,46.0,40.0,34.0,38.0,A-,SCORE_INTERDISC_ENVIRONMENT,52.0,NaN
212008,CC,COLOMBIA,M,10/08/1994,NO,20183,EK201830148018,Single,STUDENT,COLOMBIA,...,42.0,46.0,45.0,44.0,33.0,43.0,A-,SCORE_INTERDISC_ENVIRONMENT,52.0,NaN
212009,CC,COLOMBIA,M,01/01/1997,NO,20183,EK201830033403,Single,STUDENT,COLOMBIA,...,57.0,61.0,56.0,69.0,69.0,50.0,A1,SCORE_DEEPEN_MATHEMATICS,6.0,II

In [11]:
###############################################################################
### Un-comment this chunk to save the file in the data folder of this Repo. ###
### ⚠️ Caution: don't upload to GitHub, it weights more than 280 MB.        ###
###############################################################################

## Save the database translated in English
#df_2.to_csv('../../data/saber_combined_all_fields_ENG.csv')